name: "CI"

on:
  workflow_dispatch:
  push:
    branches: ['main', 'dev-*']
  pull_request:
  release:
    types: [published]

jobs:
  tests:
    name: "Docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[docs]
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: build docs
        run: |
          make docs
      - name: save docs
        uses: actions/upload-artifact@v4
        with:
          name: docs-html
          path: docs/_site

      # deploy ----

      - name: publish docs
        if: github.ref_name == 'main' && github.ref_type == 'branch'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          publish_branch: gh-pages
          destination_dir: main